#!/bin/sh

# This is the example configuration file for river.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
#riverctl map normal Super Q alacritty
riverctl map normal Super Q spawn alacritty
riverctl map normal Super F spawn firefox
# Super+C to close the focused view
riverctl map normal Super C close

# Super+R to run wofi 
riverctl map normal Super R spawn "wofi --insensitive --show drun"
# 
# Super+Shift+E to exit river
riverctl map normal Super M exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

riverctl map normal Super G spawn "~/.config/river/outputs --garage"
riverctl map normal Super O spawn "~/.config/river/outputs --office"
riverctl map normal Super B spawn "~/.config/river/outputs --bedroom"

riverctl map normal $mod1 up    send-layout-cmd wideriver "--layout monocle"
riverctl map normal $mod1 down  send-layout-cmd wideriver "--layout wide"
riverctl map normal $mod1 left  send-layout-cmd wideriver "--layout left"
riverctl map normal $mod1 right send-layout-cmd wideriver "--layout right"

riverctl map normal $mod1 Space send-layout-cmd wideriver "--layout-toggle"

riverctl map normal $mod1 plus  send-layout-cmd wideriver "--ratio +0.025"
riverctl map normal $mod1 equal send-layout-cmd wideriver "--ratio 0.35"
riverctl map normal $mod1 minus send-layout-cmd wideriver "--ratio -0.025"

riverctl map normal $mod2 plus  send-layout-cmd wideriver "--count +1"
riverctl map normal $mod2 equal send-layout-cmd wideriver "--count 1"
riverctl map normal $mod2 minus send-layout-cmd wideriver "--count -1"

riverctl map normal $mod2 e     send-layout-cmd wideriver "--stack even"
riverctl map normal $mod2 w     send-layout-cmd wideriver "--stack dwindle"
riverctl map normal $mod2 i     send-layout-cmd wideriver "--stack diminish"

# Super+[1-9] to focus tag [0-8]

# Super+Shift+[1-9] to tag focused view with tag [0-8]
# Super+Control+[1-9] to toggle focus of tag [0-8]
riverctl map normal Super 1 set-focused-tags 1
riverctl map normal Super 2 set-focused-tags 2
riverctl map normal Super 3 set-focused-tags 4
riverctl map normal Super 4 set-focused-tags 6

# Super+Control+[1-9] to toggle focus of tag [0-8]
#   riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
#    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
#done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super U toggle-fullscreen


# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300
# Set focus to always follow cursor. Options are disabled | normal | always
riverctl focus-follows-cursor always

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Fix borders
riverctl rule-add ssd
wlr-randr --output DP-1 --off
wlr-randr --output DP-2 --off
wlr-randr --output HDMI-A-1 --mode 3840x2160@120Hz --scale 2
swaybg -i ~/.wallpaper/wallhaven-l3r79p.jpg --mode fill &
# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout wideriver
wideriver --layout wide --stack diminish --count 3 --ratio 0.4 --inner-gaps 10 --outer-gaps 10 &
riverctl spawn dunst
riverctl spawn waybar
