import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
padding = { x = 4, y = 4 }

[colors]
vi_mode_cursor = { text = "#ffffff", background = "#F81CE5" }

[bell]
duration = 100
color = "#E90505"

[selection]
save_to_clipboard = true

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" },
]